version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: dnd
    ports:
      - 3309:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - db:db
    volumes:
      - ./src:/app/src
